env:
  global:
    - CC_TEST_REPORTER_ID=8a0697336093e0a0b8aed2d934527c361ac20724bcfec0e68b9fdef71db5c005
sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
before_install: gem install bundler -v 1.15.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
